### ISSUE TITLE
建议设置成早上7点运行

### ISSUE THREAD

**Issue by zpdhg** [Editi0/SYSU-HealthReport#1]
9点多很多学院已经收上名单了

**Comment by Editst** [comment]
自行调整 actions 配置文件中的 schedule 时间即可
```yaml
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 0 * * *'
```
